server:
  port: 8081

polygons:
  url: https://gist.githubusercontent.com/codeofsumit/6540cdb245bd14c33b486b7981981b7b/raw/73ebda86c32923e203b2a8e61615da3e5f1695a2/polygons.json


vehicles:
  url: http://localhost:3000/vehicles/Stuttgart

