server:
  port: 8081

polygons:
  url: https://gist.githubusercontent.com/codeofsumit/6540cdb245bd14c33b486b7981981b7b/raw/73ebda86c32923e203b2a8e61615da3e5f1695a2/polygons.json

vehicles:
  url: ${CAR-POSITION-SERVER:3000}

spring:
  kafka:
    template:
      default-topic: vehicle-position-events
    producer:
      bootstrap-servers: ${KAFKA_SERVERS:kafka-server1:9092, kafka-server2:9093, kafka-server3:9094}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
    admin:
      properties:
        bootstrap.servers: ${KAFKA_SERVERS:kafka-server1:9092, kafka-server2:9093, kafka-server3:9094}

